// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/scenarios/run": {
            "post": {
                "description": "Warms the pipeline up for the scenario's exchange/pair, produces every ` + "`" + `sources` + "`" + ` entry to ` + "`" + `ex{exchange_id}-raw` + "`" + `, then reads the snapshot, rejected and aggregated topics back and compares them to the ` + "`" + `want_*` + "`" + ` streams.\n\nJob 6 is always asserted: ` + "`" + `want_aggregated` + "`" + ` is the book the pair's ` + "`" + `p{pair_id}-asks` + "`" + ` / ` + "`" + `p{pair_id}-bids` + "`" + ` topics must END on, and every level carries the ` + "`" + `exchange_id` + "`" + ` it came from because the aggregator unions across exchanges instead of summing them. Only the final record on each side is read, not the whole stream. Omitting ` + "`" + `want_aggregated` + "`" + ` does NOT skip the check — the expectation is then derived from the last ` + "`" + `want_snapshots` + "`" + ` entry with the scenario's exchange stamped on every level, which is exact only because a scenario feeds ONE exchange. Send it explicitly to say what you mean.\n\nA scenario that does not match is **200 with ` + "`" + `\"status\":\"failed\"` + "`" + `**, not a 5xx: the run itself worked, the pipeline disagreed. A non-200 always means the scenario never ran.\n\nRuns are serialized — each one cancels the Flink jobs and recreates the exchange's topics, so a request arriving while another is in flight gets 409 instead of being queued. Expect a successful call to take minutes.\n\n\"Try it out\" is prefilled with the real ` + "`" + `ex1-precision-dust` + "`" + ` case — a nobitex REST snapshot plus a WS delta on ex1/pair 1, where two bid prices merge once truncated to the market's 2 places and a dust quantity truncates to zero and deletes its level. Send it as-is and it should come back ` + "`" + `\"status\":\"ok\"` + "`" + `.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scenarios"
                ],
                "summary": "Run one scenario",
                "parameters": [
                    {
                        "description": "The scenario to run. Unknown fields are rejected, so a mistyped want_snapshots cannot silently pass.",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/server.RunRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "The scenario ran; status says whether it matched",
                        "schema": {
                            "$ref": "#/definitions/server.RunResponse"
                        }
                    },
                    "400": {
                        "description": "Body could not be decoded or failed validation",
                        "schema": {
                            "$ref": "#/definitions/server.RunResponse"
                        }
                    },
                    "409": {
                        "description": "Another scenario is already running",
                        "schema": {
                            "$ref": "#/definitions/server.RunResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "events.AggregatedLevel": {
            "type": "object",
            "properties": {
                "exchange_id": {
                    "type": "integer"
                },
                "price": {
                    "type": "string"
                },
                "quantity": {
                    "type": "string"
                }
            }
        },
        "events.AvroTime": {
            "type": "object",
            "properties": {
                "long": {
                    "type": "string"
                }
            }
        },
        "events.OrderbookSnapshot": {
            "type": "object",
            "properties": {
                "asks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/events.PriceLevel"
                    }
                },
                "bids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/events.PriceLevel"
                    }
                },
                "event_time": {
                    "type": "string"
                },
                "exchange_id": {
                    "type": "integer"
                },
                "pair_id": {
                    "type": "integer"
                },
                "pipeline_timings": {
                    "$ref": "#/definitions/events.PipelineTimings"
                }
            }
        },
        "events.PipelineTimings": {
            "type": "object",
            "properties": {
                "PipelineTimings": {
                    "$ref": "#/definitions/events.StepTimings"
                }
            }
        },
        "events.PriceLevel": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "string"
                },
                "quantity": {
                    "type": "string"
                }
            }
        },
        "events.StepTimings": {
            "type": "object",
            "properties": {
                "book_build_in": {
                    "$ref": "#/definitions/events.AvroTime"
                },
                "book_build_out": {
                    "$ref": "#/definitions/events.AvroTime"
                },
                "pair_extract_in": {
                    "$ref": "#/definitions/events.AvroTime"
                },
                "pair_extract_out": {
                    "$ref": "#/definitions/events.AvroTime"
                },
                "precision_in": {
                    "$ref": "#/definitions/events.AvroTime"
                },
                "precision_out": {
                    "$ref": "#/definitions/events.AvroTime"
                },
                "rebase_in": {
                    "$ref": "#/definitions/events.AvroTime"
                },
                "rebase_out": {
                    "$ref": "#/definitions/events.AvroTime"
                },
                "type_validate_in": {
                    "$ref": "#/definitions/events.AvroTime"
                },
                "type_validate_out": {
                    "$ref": "#/definitions/events.AvroTime"
                }
            }
        },
        "scenario.AggregatedBook": {
            "type": "object",
            "properties": {
                "asks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/events.AggregatedLevel"
                    }
                },
                "bids": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/events.AggregatedLevel"
                    }
                }
            }
        },
        "server.RunRequest": {
            "type": "object",
            "properties": {
                "exchange_id": {
                    "type": "integer",
                    "example": 3
                },
                "ignore_event_time": {
                    "description": "IgnoreEventTime blanks EventTime on both sides before comparing. Only ex3\nwallex needs it: its wire carries no timestamp at all, so job 1 stamps\nprocessing time and the field is wall-clock. The levels are still asserted.",
                    "type": "boolean"
                },
                "name": {
                    "type": "string",
                    "example": "ex3-half-book"
                },
                "pair_id": {
                    "type": "integer",
                    "example": 1
                },
                "sources": {
                    "description": "raw exchange documents, verbatim",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "want_aggregated": {
                    "description": "WantAggregated is the aggregated view of the pair once every source is\nthrough — the last record on ` + "`" + `p{PairID}-asks` + "`" + ` and on ` + "`" + `p{PairID}-bids` + "`" + `.\nEvery scenario in this package spells it out, and a posted one should too.\nNil does NOT mean \"skip job 6\": the expectation is then DERIVED from the\nlast wanted snapshot, which is what the aggregated book must be when a\nsingle exchange feeds the pair.\nOnly the final state is read — the aggregator emits one record per side\nper snapshot, so asserting the whole stream would restate WantSnapshots\ntwice over.",
                    "allOf": [
                        {
                            "$ref": "#/definitions/scenario.AggregatedBook"
                        }
                    ]
                },
                "want_rejects": {
                    "description": "reject_reason of each dead-letter, e.g. \"sequence_gap\"",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "want_snapshots": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/events.OrderbookSnapshot"
                    }
                }
            }
        },
        "server.RunResponse": {
            "type": "object",
            "properties": {
                "duration_ms": {
                    "type": "integer",
                    "example": 92310
                },
                "error": {
                    "type": "string"
                },
                "name": {
                    "type": "string",
                    "example": "ex3-half-book"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ok",
                        "failed"
                    ],
                    "example": "ok"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9595",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Orderbook E2E Harness API",
	Description:      "Runs one end-to-end scenario against the normalizer pipeline: the stack is provisioned once when the server starts, then every request warms the pipeline up for its own exchange/pair, feeds the raw topic and checks what came back out.\n\nThe same `Scenario` the compiled-in cases use, posted as JSON. Regenerate this spec with `swag init -g main.go -o docs` after changing the handler or the scenario struct.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
